---
- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- package:
    name: "{{ item }}"
    state: present
  with_items:
     - git
     - wget
     - unzip
     - gcc
     - make
     - openvswitch
     - docker
     - libpcap-devel
     - libxml2-devel
     - screen
     - inotify-tools
     - iperf
     - libselinux-python
     - bridge-utils
     - perl-Graph-Easy
     - rpm-build
     - rpmlint
     - libvirt
     - libvirt-devel
     - libvirt-client
     - vagrant-libvirt
     - ansible
     - numactl-devel
     - kernel-devel
     - python3-virtualenv
     - llvm-devel
     - clang-devel
     - bcc-devel
     - elfutils-libelf-devel
     - kubernetes-client
     - jq
     - aria2
     - tcpdump
     - socat
     - python2-virtualenv
     - python3-virtualenv
     - virt-what
     - selinux-policy-devel
     - policycoreutils-devel
     - mock
     - dnf-utils
     - manifest-tool
     - ffmpeg
     - npm
     - gifsicle
     - podman

- service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - openvswitch
    - docker

- include_tasks: lxd.yml
  when: ansible_distribution == "Fedora" and ansible_architecture == "x86_64"

- include_tasks: protobuf.yml

- include_tasks: static.yml

- include_tasks: gimme.yml
  tags:
    - vagrant

- include_tasks: docker.yml
  tags:
    - vagrant

- include_tasks: vpp.yml

- include_tasks: virtualbox.yml
