---
- name: Install Docker
  package:
    name: docker
    state: present

- name: Enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Run docker registry
  shell: "docker run -d -p 5000:5000 --restart=always --name registry registry:2"
  when: '"file://" in skydive_binary_remote_location'

- name: Set facts
  set_fact: "skydive_docker_registry=localhost:5000"
  when: '"file://" in skydive_binary_remote_location'

- name: Copy docker image
  copy:
    src: "{{ skydive_binary_remote_location | replace('file://', '') }}"
    dest: /tmp
    force: true
    mode: 0755
  when: '"file://" in skydive_binary_remote_location'

- name: Import skydive image
  shell: "docker load -i /tmp/{{ skydive_binary_remote_location | replace('file://', '') | basename }}"
  when: '"file://" in skydive_binary_remote_location'

- name: Tag skydive image
  shell: "docker tag skydive/skydive:devel {{ skydive_docker_registry }}/{{ skydive_analyzer_docker_image }}:{{ skydive_docker_image_tag }}"
  when: '"file://" in skydive_binary_remote_location'

- name: Push skydive image to registry
  shell: "docker push {{ skydive_docker_registry }}/{{ skydive_analyzer_docker_image }}:{{ skydive_docker_image_tag }}"
  when: '"file://" in skydive_binary_remote_location'

- name: Create systemd unit file
  include_role:
    name: skydive_common
    tasks_from: systemd
  vars:
    service_name: skydive-analyzer
    exec_start_pre: /usr/bin/docker stop skydive-analyzer-{{ ansible_hostname }}
    exec_start: |
      /usr/bin/docker run --rm \
        {{ skydive_analyzer_docker_extra_env }} --name=skydive-analyzer-{{ ansible_hostname }} \
        -v /etc/skydive/skydive.yml:/etc/skydive.yml \
        -p {{ skydive_analyzer_port }}:{{ skydive_analyzer_port }} \
        -p {{ skydive_analyzer_port }}:{{ skydive_analyzer_port }}/udp \
        -p {{ skydive_etcd_port }}:{{ skydive_etcd_port }} \
        {{ skydive_docker_registry }}/{{ skydive_analyzer_docker_image }}:{{ skydive_docker_image_tag }} \
        {{ skydive_analyzer_docker_command }}
    exec_stop_post: /usr/bin/docker stop skydive-analyzer-{{ ansible_hostname }}
